### ISSUE TITLE
Improve Dungeon Selection

### ISSUE THREAD

**Issue by dmansdman** [ewang2002/OneLifeBot#48]
Make it easier to select commonly ran dungeons (o3, halls, shatts, nests).

Separate them from the other random dungeons in the dropdown.

**Comment by dmansdman** [comment]
@ewang2002 Thoughts on a) giving exaltation a dedicated dropdown,  b) placeholder text

![image](https://user-images.githubusercontent.com/97406520/148791845-c129dd68-9435-4885-b537-51e51da23641.png)

**Comment by dmansdman** [comment]
Also, StartHeadcount and StartAFKCheck are virtually identical.  There should be a way to essentially combine them such that the code doesn't exist twice.

**Comment by ewang2002** [comment]
@dmansdman Yes, we can do that. In fact, note that I have classified dungeons based on dungeon type (e.g. Godland dungeons, basic dungeons, and so on). You can use that to sort where exaltation dungeons can go. But yeah, that's good!

And yes, I agree that we should combine the two commands. The reason why I essentially copied them is because some people may not be used to having AFK Check & Headcount in the same command.

**Comment by dmansdman** [comment]
I noticed the dungeon classification, that is how I am currently identifying the exaltation dungeons.

I wasn't necessarily suggesting we combine commands, just how we handle them in the backend.  I'm not comfortable enough yet to fully realize the idea, but I think we can consolidate the run methods of each such that they reference common functions like getting the dungeon, getting channel, etc.  This way, the run methods would be succinct and not duplicate each other.  You would probably know better than me whether this is easy/feasible.

**Comment by ewang2002** [comment]
Ok, cool (for the first part).

Considering that there's a ton of duplicate code, yeah I agree, and I also think it's feasible. For example, notice how I separated the code out by "steps" if that makes sense (e.g. "// Step 1: Find all sections that the leader can lead in"). I think those are good ways to refactor the code -- take each step and make it a function that both commands can refer to.
